MAXCACHEAGEHOURS = 23   #Age to expire cache files.
ANALYSISPERIOD = 80     #Number of days to watch price after a check trigger
MAIL_USER = 'XXXXXXXXXXX@gmail.com'
MAIL_PASSWORD = 'XXXXXXXXXXXXXXXX'
MAIL_SMTPHOST = 'smtp.gmail.com'
MAIL_SMTPPORT = 465
API_KEY = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
Email_Report_Address = ['your@email.com']
OUT_CSV_FILE = "/home/user/py/pyPriceAgent/latestPrices.csv"
OUT_HTML_FILE = "/home/user/py/pyPriceAgent/latestPrices.html"
TickersName = "myTickers.txt"
DoSafeFileWrite = True 
